services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/n8n-io/n8n
    region: oregon  # Atau frankfurt
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: password123
      - key: WEBHOOK_URL
        value: https://n8n-<your-app-name>.onrender.com/
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: VUE_APP_URL_BASE_API
        value: https://n8n-<your-app-name>.onrender.com/
    dockerfilePath: ./Dockerfile
